on:
  workflow_run:
    workflows: [ "Build" ]
    types:
      - completed
    branches:
      - main

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
    permissions:
      contents: write
      pull-requests: write
